services:
    guru_phone_number_formatter.formatter:
        class: Guru\PhoneNumberFormatterBundle\Formatter\Formatter
        arguments: [@service_container]
        public: false
        calls:
            - [setCountryCodes, [%guru_phone_number_formatter.country_codes%]]
            - [addRegionFormatter, ['my', @guru_phone_number_formatter.formatter_my]]
            - [addRegionFormatter, ['id', @guru_phone_number_formatter.formatter_id]]
            - [addRegionFormatter, ['th', @guru_phone_number_formatter.formatter_th]]
            - [addRegionFormatter, ['sg', @guru_phone_number_formatter.formatter_sg]]
    guru_phone_number_formatter.formatter_my:
        class: Guru\PhoneNumberFormatterBundle\Formatter\FormatterMy
        arguments: [@service_container]
        public: false
        calls:
            - [setLandlinePrefixCodesShort, [%guru_phone_number_formatter.format.my.prefix.landline.short%]]
            - [setLandlinePrefixCodesLong, [%guru_phone_number_formatter.format.my.prefix.landline.long%]]
            - [setMobilePrefixCodesShort, [%guru_phone_number_formatter.format.my.prefix.mobile.short%]]
            - [setMobilePrefixCodesLong, [%guru_phone_number_formatter.format.my.prefix.mobile.long%]]
    guru_phone_number_formatter.formatter_id:
        class: Guru\PhoneNumberFormatterBundle\Formatter\FormatterId
        arguments: [@service_container]
        public: false
        calls:
            - [setLandlineLengths, [%guru_phone_number_formatter.format.id.prefix.landline.lengths%]]
            - [setLandlinePrefixCodesShort, [%guru_phone_number_formatter.format.id.prefix.landline.short%]]
            - [setLandlinePrefixCodesLong, [%guru_phone_number_formatter.format.id.prefix.landline.long%]]
            - [setMobileCodes, [%guru_phone_number_formatter.format.id.prefix.mobile%]]
    guru_phone_number_formatter.formatter_th:
        class: Guru\PhoneNumberFormatterBundle\Formatter\FormatterTh
        arguments: [@service_container]
        public: false
        calls:
            - [setLandlineNumberLength, [%guru_phone_number_formatter.format.th.landline.length%]]
            - [setLandlinePrefixCodes, [%guru_phone_number_formatter.format.th.prefix.landline%]]
            - [setMobileNumberLength, [%guru_phone_number_formatter.format.th.mobile.length%]]
            - [setMobilePrefixCodes, [%guru_phone_number_formatter.format.th.prefix.mobile%]]
    guru_phone_number_formatter.formatter_sg:
        class: Guru\PhoneNumberFormatterBundle\Formatter\FormatterSg
        arguments: [@service_container]
        public: false
        calls:
            - [setNumberLength, [%guru_phone_number_formatter.format.sg.length%]]
            - [setLandlinePrefix, [%guru_phone_number_formatter.format.sg.prefix.voip%]]
            - [setVoipPrefix, [%guru_phone_number_formatter.format.sg.prefix.landline%]]
            - [setMobileRules, [%guru_phone_number_formatter.format.sg.mobile.rules%]]
